"""update database

Revision ID: 3c31bbe78fc8
Revises: c72d219f1e4a
Create Date: 2025-08-29 16:18:35.846598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c31bbe78fc8'
down_revision: Union[str, None] = 'c72d219f1e4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Care_events', sa.Column('name', sa.String(length=50), nullable=False))
    op.create_unique_constraint(None, 'Care_events', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Care_events', type_='unique')
    op.drop_column('Care_events', 'name')
    # ### end Alembic commands ###
